# Generated by Django 3.0.8 on 2020-11-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stock',
            new_name='stock_symbol',
        ),
    ]
