# Generated by Django 3.1.4 on 2021-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20201226_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='buy', max_length=4),
        ),
    ]
